#! /bin/sh
#!perl -w # --*- Perl -*--
eval 'exec perl -x $0 ${1+"$@"}'
    if 0;
#------------------------------------------------------------------------------
#$Author$
#$Date$ 
#$Revision$
#$URL$
#------------------------------------------------------------------------------
#*
#  Convert Unicode characters into CIF escape sequences.
#**

use strict;
use lib "./lib/perl5";
use Unicode2CIF;

use open ":utf8";

binmode( STDIN,  ":utf8" );
binmode( STDOUT, ":utf8" );

while(<>) {
    print Unicode2CIF::unicode2cif( $_ );
}
