
clipper_util.h:         	clipper_precision.h clipper_sysdep.h 

clipper_util.o:         	clipper_util.cpp clipper_util.h 

clipper_message.h:      	

clipper_message.o:      	clipper_message.cpp clipper_message.h 

clipper_memory.h:       	clipper_message.h 

clipper_memory.o:       	clipper_memory.cpp clipper_memory.h 

clipper_stats.h:        	clipper_types.h 

clipper_stats.o:        	clipper_stats.cpp clipper_stats.h 

clipper_types.h:        	clipper_util.h clipper_memory.h 

clipper_types.o:        	clipper_types.cpp clipper_types.h 

rotation.h:             	clipper_types.h 

rotation.o:             	rotation.cpp rotation.h 

ramachandran.h:         	clipper_types.h 

ramachandran.o:         	ramachandran.cpp ramachandran.h 

cell.h:                 	clipper_types.h 

cell.o:                 	cell.cpp cell.h 

symop.h:                	clipper_types.h 

symop.o:                	symop.cpp symop.h coords.h 

spacegroup_data.h:      	

spacegroup_data.o:      	spacegroup_data.cpp spacegroup_data.h 

spacegroup.h:           	symop.h spacegroup_data.h 

spacegroup.o:           	spacegroup.cpp spacegroup.h coords.h 

coords.h:               	cell.h spacegroup.h clipper_stats.h 

coords.o:               	coords.cpp coords.h spacegroup.h rotation.h 

derivs.h:               	coords.h 

derivs.o:               	derivs.cpp derivs.h 

hkl_lookup.h:           	coords.h 

hkl_lookup.o:           	hkl_lookup.cpp hkl_lookup.h 

hkl_info.h:             	hkl_lookup.h 

hkl_info.o:             	hkl_info.cpp hkl_info.h 

hkl_data.h:             	hkl_info.h 

hkl_data.o:             	hkl_data.cpp hkl_data.h 

hkl_datatypes.h:        	hkl_data.h 

hkl_datatypes.o:        	hkl_datatypes.cpp hkl_datatypes.h 

hkl_compute.h:          	hkl_datatypes.h 

hkl_compute.o:          	hkl_compute.cpp hkl_compute.h 

hkl_operators.h:        	hkl_datatypes.h 

hkl_operators.o:        	hkl_operators.cpp hkl_operators.h 

resol_fn.h:             	hkl_data.h 

resol_fn.o:             	resol_fn.cpp resol_fn.h 

resol_basisfn.h:        	resol_fn.h 

resol_basisfn.o:        	resol_basisfn.cpp resol_basisfn.h 

resol_targetfn.h:       	resol_basisfn.h hkl_datatypes.h 

resol_targetfn.o:       	resol_targetfn.cpp resol_targetfn.h 

fftmap.h:               	coords.h 

fftmap.o:               	fftmap.cpp fftmap.h hkl_datatypes.h 

fftmap_sparse.h:        	coords.h 

fftmap_sparse.o:        	fftmap_sparse.cpp fftmap_sparse.h hkl_datatypes.h 

xmap.h:                 	fftmap.h fftmap_sparse.h derivs.h 

xmap.o:                 	xmap.cpp xmap.h 

nxmap.h:                	derivs.h 

nxmap.o:                	nxmap.cpp nxmap.h 

nxmap_operator.h:       	xmap.h nxmap.h 

nxmap_operator.o:       	nxmap_operator.cpp nxmap_operator.h 

map_interp.h:           	derivs.h 

map_interp.o:           	map_interp.cpp map_interp.h 

map_utils.h:            	derivs.h 

map_utils.o:            	map_utils.cpp map_utils.h xmap.h nxmap.h 

atomsf.h:               	coords.h 

atomsf.o:               	atomsf.cpp atomsf.h 

container.h:            	coords.h 

container.o:            	container.cpp container.h 

container_types.h:      	container.h 

container_types.o:      	container_types.cpp container_types.h 

container_hkl.h:        	container_types.h hkl_data.h 

container_hkl.o:        	container_hkl.cpp container_hkl.h 

container_map.h:        	container_types.h nxmap_operator.h 

container_map.o:        	container_map.cpp container_map.h 

