---
abstract: 'Perl bindings for nauty'
author:
  - 'Andrius Merkys <merkys@cpan.org>'
build_requires:
  Graph::Undirected: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.010, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Graph-Nauty
requires:
  Data::Dumper: '0'
  Graph::Undirected: '0'
  Scalar::Util: '0'
  perl: '5.008'
resources:
  bugtracker: https://github.com/merkys/graph-nauty/issues
  homepage: http://search.cpan.org/dist/
  repository: git://github.com/merkys/graph-nauty.git
version: 0.3.3
x_serialization_backend: 'YAML::Tiny version 1.70'
