#!/usr/bin/python
# -*- coding: utf-8 -*-
#------------------------------------------------------------------------------
#$Author$
#$Revision$
#$URL$
#$Date$
#$Id$
#------------------------------------------------------------------------------
#*
#  Test driver for pycodcif module.
#**
import sys
from pycodcif import parse

filename = sys.argv.pop()
options = {}
for arg in sys.argv[1:]:
    options[arg] = 1

parse( filename, options )
