#!/usr/bin/python
# -*- coding: utf-8 -*-
#------------------------------------------------------------------------------
#$Author$
#$Revision$
#$URL$
#$Date$
#$Id$
#------------------------------------------------------------------------------
#*
#  Test driver for pycodcif module.
#**
import re
import sys
from pycodcif import parse, CifParserException

options = {}
filenames = []
debug = False

options = {}
for arg in sys.argv[1:]:
    if arg == '--debug':
        debug = True
    elif arg.startswith('--'):
        options[re.sub('-','_',re.sub('--','',arg))] = 1
    else:
        filenames.append(arg)

try:
    parse( filenames[0], options )
except CifParserException as e:
    pass
