#! /bin/sh
#!perl -w # --*- Perl -*--
eval 'exec perl -x $0 ${1+"$@"}'
    if 0;
#------------------------------------------------------------------------------
#$Author$
#$Date$ 
#$Revision$
#$URL$
#------------------------------------------------------------------------------
#*
#  Test driver for COD::CIF::Parser::Bison.pm module.
#**
use strict;
use warnings;
use COD::CIF::Parser::Bison;

binmode( STDOUT, ":encoding(UTF-8)" );
binmode( STDERR, ":encoding(UTF-8)" );

my $parser = new COD::CIF::Parser::Bison;
my $file = pop @ARGV;
$parser->Run( $file, { map { $_ => 1 } @ARGV } );

