targets = [ 'ccad', 'cfft', 'csigmaa', 'sftest', 'ffttest', 'mtztest', 'phstest', 'rfltest', 'symtest', 'maptest', 'sktest', 'ciftophs' ]

Import( 'env_examples' )

for target in targets:
  env_examples.Program( target, target+'.cpp' )
