/* *****************************************************
   THIS IS AN AUTOMATICALLY GENERATED FILE. DO NOT EDIT.
   *****************************************************

   Generated by:
     cctbx.source_generators.flex_fwd_h
 */

#ifndef CCTBX_BOOST_PYTHON_FLEX_FWD_H
#define CCTBX_BOOST_PYTHON_FLEX_FWD_H

#include <scitbx/array_family/boost_python/flex_fwd.h>

#if defined(__GNUC__) && __GNUC__ == 3 && __GNUC_MINOR__ == 2
// work around weird gcc 3.2 problem:
//   def.hpp must be included before boost/math/special_functions/atanh.hpp
//   (as of boost svn revison 39792)
#include <boost/python/def.hpp>
#endif

#endif // CCTBX_BOOST_PYTHON_FLEX_FWD_H
