#! /bin/sh
#!perl -w # --*- Perl -*--
eval 'exec perl -x $0 ${1+"$@"}'
    if 0;
#------------------------------------------------------------------------------
#$Author$
#$Date$ 
#$Revision$
#$URL$
#------------------------------------------------------------------------------
#*
#  Convert CIF escape sequences into Unicode characters.
#**

use strict;
use warnings;
use COD::CIF::Unicode2CIF qw( cif2unicode );
use COD::SOptions qw( getOptions );
use COD::SUsage qw( usage );

#* USAGE:
#*     $0 input1.cif input*.cif
#*
#* OPTIONS:
#* --help, --usage
#*     Print a short usage message (this message) and exit.
#**
@ARGV = getOptions(
    "--help,--usage"    => sub { usage; exit }
);

use open ":utf8";

binmode( STDIN,  ":utf8" );
binmode( STDOUT, ":utf8" );

while(<>) {
    print cif2unicode( $_ );
}
