#! /bin/sh
#!perl -w # --*- Perl -*--
eval 'exec perl -x $0 ${1+"$@"}'
    if 0;
#------------------------------------------------------------------------------
#$Author$
#$Revision$
#$URL$
#$Date$
#------------------------------------------------------------------------------
#*
#* Reads the quotient graph representation from a CIF file and converts it to
#* the net representation in the .cgd structure file format.
#*
#* The cgd format contains definition of nets. The first two columns are node
#* ids, the rest are translations. This is one of the formats accepted by the
#* Systre program [1].
#*
#* [1] http://gavrog.org/Systre-Help.html#file_formats,
#      [Last accessed: 2024-09-17]
#*
#* USAGE:
#*    $0 [options] input.cif [input2.cif ...]
#**

use strict;
use warnings;

use COD::CIF::Parser qw( parse_cif );
use COD::CIF::Tags::CanonicalNames qw( canonicalize_all_names );
use COD::UserMessage qw( error );
use COD::SOptions qw( getOptions );
use COD::SUsage qw( usage options );
use COD::ToolsVersion qw( get_version_string );

my $use_parser = 'c';
@ARGV = getOptions(

#* OPTIONS:
#*
#*   --use-c-parser
#*                     Use Perl & C parser for CIF parsing (default).
#*   --use-perl-parser
#*                     Use Perl parser for CIF parsing.
#*   --help, --usage
#*                     Output a short usage message (this message) and exit.
#*   --version
#*                     Output version information and exit.
#**

    '--use-perl-parser' => sub { $use_parser = 'perl' },
    '--use-c-parser'    => sub { $use_parser = 'c' },
    '--help,--usage'    => sub { usage(); exit },
    '--version'         => sub { print get_version_string(), "\n"; exit },
);

@ARGV = ( '-' ) unless @ARGV;

binmode STDOUT, ':encoding(UTF-8)';
binmode STDERR, ':encoding(UTF-8)';

for my $filename (@ARGV) {

    my $options = { 'parser' => $use_parser, 'no_print' => 1 };
    my ( $data, $err_count, $messages ) = parse_cif( $filename, $options );

    if ( $err_count > 0 ) {
        print STDERR $_ foreach ( @{$messages} );
        error( {
            'program'  => $0,
            'filename' => $filename,
            'message'  =>
                "$err_count error(s) encountered while parsing the file"
        } );
        next;
    }
    print STDERR $_ foreach ( @{$messages} );

    canonicalize_all_names( $data, $options );

    foreach( @{$data} ) {
        next unless exists $_->{values}{'_topol_atom.atom_label'};
        my @atoms = @{ $_->{values}{'_topol_atom.atom_label'} };
        my @destinations = @{ $_->{values}{'_topol_atom.atom_edge_destination_label'} };
        my @labels = @{ $_->{values}{'_topol_atom.edge_label'} };
        my $id = $_->{name};
        my $cgd_file = convert_to_cgd(\@atoms, \@destinations, \@labels, $id);
        print $cgd_file;
    }
}

sub convert_to_cgd {
    my @atoms = @{ shift @_ };
    my @destinations = @{ shift @_ };
    my @labels = @{ shift @_ };
    my $id = shift @_;
    my @cgd_lines = ('PERIODIC_GRAPH', "ID $id", 'EDGES');
    my %label_to_number;
    my $current_number = 0;

    for my $i (0..$#atoms) {
        my $atom_label = $atoms[$i];
        my $dest_label = $destinations[$i];
        my ($x, $y, $z) = split /,/, $labels[$i];

        $label_to_number{$atom_label} //= ++$current_number;
        $label_to_number{$dest_label} //= ++$current_number;

        push @cgd_lines, "  $label_to_number{$atom_label} $label_to_number{$dest_label} $x $y $z";
    }

    push @cgd_lines, "END\n";
    return join("\n", @cgd_lines);
}
