#! /bin/sh
#!perl -w # --*- Perl -*--
eval 'exec perl -x $0 ${1+"$@"}'
    if 0;
#------------------------------------------------------------------------------
#$Author$
#$Date$ 
#$Revision$
#$URL$
#------------------------------------------------------------------------------
#*
#  Parse a CIF file.
#**

use strict;
use warnings;
use COD::CIF::Parser qw( parse_cif );
use COD::SOptions;
use COD::SUsage qw(usage options);
use COD::ShowStruct;

my $use_parser = 'c';

#* USAGE:
#*     $0 --options input1.cif input*.cif
#*
#* OPTIONS:
#* --use-perl-parser
#*                     Use development CIF parser written in Perl.
#* --use-c-parser
#*                     Use faster C/Yacc CIF parser (default).
#*
#* --help, --usage
#*                     Print a short usage message (this message) and exit.
#**
@ARGV = getOptions(
    "--use-perl-parser" => sub { $use_parser = "perl" },
    "--use-c-parser"    => sub { $use_parser = "c" },
    "--options"         => sub { options; exit },
    "--help,--usage"    => sub { usage; exit }
);

@ARGV = ("-") unless @ARGV;

foreach my $filename ( @ARGV ) {

    my ( $data ) = parse_cif( $filename, { parser => $use_parser } );

    for my $dataset (@$data) {
        showRef( $dataset );
    }
}
