#! /bin/sh
#!perl -w # --*- Perl -*--
eval 'exec perl -x $0 ${1+"$@"}'
    if 0;
#------------------------------------------------------------------------------
#$Author$
#$Date$ 
#$Revision$
#$URL$
#------------------------------------------------------------------------------
#*
#  Calculate Z value (i.e. the number of "chemical fomula units" in the unit cell
#  using the provided cell volume, crystal density and molecular weight.
#**

use strict;
use COD::CIF::Parser::Yapp;
use COD::CIF::Data::EstimateZ;

@ARGV = ( "-" ) unless @ARGV;

for my $filename (@ARGV) {

    my $parser = new COD::CIF::Parser::Yapp;

    my $data = $parser->Run($filename, { fix_errors => 1 });

    for my $dataset (@$data) {
        eval {
            print cif_estimate_z( $dataset ), "\n";
        };
        if( $@ ) {
            print STDERR $@;
        }  
    }
}

