#! /bin/sh
#!perl -w # --*- Perl -*--
eval 'exec perl -x $0 ${1+"$@"}'
    if 0;
#------------------------------------------------------------------------------
#$Author$
#$Date$ 
#$Revision$
#$URL$
#------------------------------------------------------------------------------
#*
#  Parse a CIF file
#**

use strict;
use COD::CIF::Parser::Yapp;
use COD::ShowStruct;

my $filename = shift(@ARGV);

my $parser = new COD::CIF::Parser::Yapp;

my $data = $parser->Run($filename);


for my $dataset (@$data) {
    showRef( $dataset );
}
