#!/bin/sh
#------------------------------------------------------------------------------
#$Author$
#$Date$ 
#$Revision$
#$URL$
#------------------------------------------------------------------------------
#*
# Extract essential data from the input CIF file and format it
# using the rules of the Crystallography Open Database (COD).
#
# USAGE: $0 --options input.cif
# USAGE: $0 --options input1.cif input*.cif
#**

set -ue
# set -x

arg=""

#* OPTIONS:
#* --help, --usage
#*     Print a short help message (this message) and exit.
#*
#* NOTE: this script also accepts all options from the 'cif_filter' script.
#**
while [ $# -gt 0 ]
do
  case $1 in
      --help|--hel|--he|--h|--usage)
          gawk '/^#\*/,/^#\*\*/ {
                  sub("^ *#[*]?[*]?", ""); \
                  gsub("\\$0","'$0'"); \
                  print $0
              }' $0
          exit
          ;;
      *)
          if [ -z ${file+1} ];
          then
             file=$1
          else
             arg="$arg $1"
          fi
          ;;
    esac
    shift
done

arg="$file $arg"

if head $file | grep -q '^#' > /dev/null 2>&1
then
    awk '{if( match( $0, "^#" )) print; else exit}' $file
else
    cat <<EOF
#------------------------------------------------------------------------------
#\$Date\$
#\$Revision\$
#\$URL\$
#------------------------------------------------------------------------------
#
# This file is available in the Crystallography Open Database (COD),
# http://www.crystallography.net/
#
# All data on this site have been placed in the public domain by the
# contributors.
#
EOF
fi

NUMBER=`basename ${file} .cif | sed -e 's/[^0-9]//g'`

cif_filter \
    --renumber \
    --start-data="${NUMBER}" \
    --exclude-empty-non-loop-tags \
    --estimate-spacegroup \
    --reformat-spacegroup \
    --keep-unrecognised-spacegroup \
    --parse-formula-sum \
    --calculate-cell-volume \
    --use-all-datablocks \
    ${arg}
