#! /bin/sh
#!perl -w # --*- Perl -*--
eval 'exec perl -x $0 ${1+"$@"}'
    if 0;
#------------------------------------------------------------------------------
#$Author$
#$Date$ 
#$Revision$
#$URL$
#------------------------------------------------------------------------------
#*
#  Perl script ...
#**

use strict;
use warnings;
use COD::Formulae::Parser::IUCr;

my $p = new COD::Formulae::Parser::IUCr;

$p->Run($ARGV[0]);
$p->PrintFormula;
