#! /bin/sh
#!perl -w # --*- Perl -*--
eval 'exec perl -x $0 ${1+"$@"}'
    if 0;
#------------------------------------------------------------------------------
#$Author$
#$Date$ 
#$Revision$
#$URL$
#------------------------------------------------------------------------------
#*
#  Check superspace group symmetry operator syntax.
#**

use strict;
use warnings;
use COD::SOptions qw( getOptions );
use COD::SUsage qw( usage );
use COD::Spacegroups::Symop::SSGParse qw( check_symmetry_operator );
use COD::ToolsVersion;

#* USAGE: $0 < input.symop
#* USAGE: $0 input.symop
#* USAGE: $0 input1.symop input*.symop
#*
#* OPTIONS:
#* --help, --usage    Print short usage message (this message) and exit.
#**
@ARGV = getOptions(
    "--help,--usage" => sub { usage; exit },
    '--version'      => sub { print 'cod-tools version ',
                              $COD::ToolsVersion::Version, "\n";
                              exit }
);

while(<>) {
    next if /^#/;
    next if /^\s*$/;
    chomp;
    print "\n# $_\n";
    my $message;
    if( ($message = check_symmetry_operator( $_ )) ) {
        print $message, "\n";
    } else {
        print "OK\n";
    }
}
