#! /bin/sh
#!perl -w # --*- Perl -*--
eval 'exec perl -x $0 ${1+"$@"}'
    if 0;
#------------------------------------------------------------------------------
#$Author$
#$Date$ 
#$Revision$
#$URL$
#------------------------------------------------------------------------------
#*
#  Parse superspacegoup symmetry operators as described in the CIF
#  _space_group_symop_ssg_operation_algebraic data items and procued
#  symmetry matrices for them.
#**

use strict;
use warnings;

use COD::Spacegroups::Symop::SSGParse;

while(<>) {
    next if /^#/;
    next if /^\s*$/;
    chomp;
    print "\n# $_\n";
    print symop_string_canonical_form( $_ ), "\n";
}
