#! /bin/sh
#!perl -w # --*- Perl -*--
eval 'exec perl -x $0 ${1+"$@"}'
    if 0;
#------------------------------------------------------------------------------
#$Author$
#$Date$ 
#$Revision$
#$URL$
#------------------------------------------------------------------------------
#*
#  Check superspace group symmetry operator syntax.
#**

use strict;
use warnings;
use COD::SOptions;
use COD::SUsage;

#* USAGE: $0 < input.symop
#* USAGE: $0 input.symop
#* USAGE: $0 input1.symop input*.symop
#*
#* OPTIONS:
#* --help, --usage    Print short usage message (this message) and exit.
#**
@ARGV = getOptions(
   "--help,--usage"  => sub { usage; exit }
);

use COD::Spacegroups::Symop::SSGParse;

while(<>) {
    next if /^#/;
    next if /^\s*$/;
    chomp;
    print "\n# $_\n";
    my $message;
    if( ($message = check_symmetry_operator( $_ )) ) {
        print $message, "\n";
    } else {
        print "OK\n";
    }
}
