#! /bin/sh
#------------------------------------------------------------------------------
#$Author$
#$Date$ 
#$Revision$
#$URL$
#------------------------------------------------------------------------------
#*
#* Print a CIF file, but omit the values of the provided CIF-like tag;
#* take into account values that are on the next line and that may span
#* several lines. Only works properly with CIF tags that are not a part
#* of a loop structure.
#*
#* USAGE: $0 _tag_name < input.cif
#* USAGE: $0 _tag_name input.cif
#* USAGE: $0 _tag_name input1.cif input*.cif
#*
#* OPTIONS:
#* --help, --usage
#*     Print a short help message (this message) and exit.
#**
while [ $# -gt 0 ]
do
  case $1 in
      --help|--hel|--he|--h|--usage)
          gawk '/^#\*/,/^#\*\*/ {
                  sub("^ *#[*]?[*]?", ""); \
                  gsub("\\$0","'$0'"); \
                  print $0
              }' $0
          exit
          ;;
      -?*) echo "`basename $0`:: ERROR, unknown option '$1'." >&2 ; exit 1 ;;
      *)
          if [ -z "$PATTERN" ];
          then
             PATTERN=$1;
          else
             FILES="$FILES $1"
          fi
          ;;
    esac
    shift
done

awk "/${PATTERN}/ {
        if( NF == 1 ) {
            getline
        }
        if( match( \$0, \"^;\" )) {
            getline
            while( !match( \$0, \"^;\" )) {
                getline
            }
        }
        next
    }
    !/${PATTERN}/ { print }
" $FILES
