#! /bin/sh
#!perl -w # --*- Perl -*--
eval 'exec perl -x $0 ${1+"$@"}'
    if 0;

#------------------------------------------------------------------------------
#$Author: adriana $
#$Date: 2010-05-30 08:18:18 +0300 (Sun, 30 May 2010) $
#$Revision: 1280 $
#$URL: svn://vartai.ibt.lt/cif-tools/trunk/perl-scripts/cif_fix_enum $
#------------------------------------------------------------------------------
#*
#  Fixes enumeration values in CIF file against CIF dictionaries.
#**

use strict;
use warnings;
use lib "./lib/perl5";
use lib "./CIFParser";
use CIFParser;
use CIFTagCanonicalNames;
use ShowStruct;
use SOptions;
use CIFTagPrint;

my $CIFfile = ();
my $CIFtags;
my $outputFile;
my $dictFiles = [];
my $setOfEnum = [];
my $dictFilesParsed = [];
my $dictTags = {};
my $parser = new CIFParser;

my $Id = '$Id: cif_fix_values 1391 2010-09-07 12:51:13Z saulius $';
my $keep_tag_order = 0;

my @dictionary_tags = ( @CIFDictTags::tag_list, @CIFCODTags::tag_list );
my %dictionary_tags = map { $_, $_ } @dictionary_tags;

#*Usage:
#*      cif_fix_enum [options] COD-cif-dir/
#*
#*Options:
#*     --dictionary cif_core.dic
#*        Any valid CIF file, with CIF dictionary (according to DDL2).
#*        You can define any number of CIF dictionaries, in a way like 
#*        this:
#*        $0 --dictionary cif_core.dic --dictionary cod_core.dic
#*     --add-dictionary cif_core.dic
#*        You can add CIF dictionary, in a way like 
#*        this:
#*        $0 --add-dictionary cif_core.dic
#*     --clear-dictionaries
#*
#**

@ARGV = getOptions(
        "--keep-tag-order" 
            => sub { $keep_tag_order = 1; },
        "--sort-tags"      
            => sub { $keep_tag_order = 0; },
       # "-d,--dictionary"
       #     => sub{ @dictionaries = (&getValue) },
       # "-D,--add-dictionaries"
       #     => \@dictionaries,
       # "--clear-dictionaries"
       #     => sub{ @dictionaries = () },
);

@ARGV = ("-") unless @ARGV;

for my $filename (@ARGV) {
    my $parser = new CIFParser;
    my $data = $parser->Run($filename);

    if( defined $parser->YYData->{ERRCOUNT} &&
        $parser->YYData->{ERRCOUNT} > 0 ) {
	print STDERR "$0: $filename: ",
	$parser->YYData->{ERRCOUNT},
	" error(s) encountered while parsing CIF data\n";
	## exit -1;
	next;
    }
    
    canonicalize_all_names( $data );
    for my $dataset (@$data) {
        my $values = $dataset->{values};
        
        # ...
    
    
    print_cif( $dataset, {
            exclude_misspelled_tags => 0,
            preserve_loop_order => 1,
            fold_long_fields => 0,
            dictionary_tags => \%dictionary_tags,
            dictionary_tag_list => \@dictionary_tags,
            keep_tag_order => $keep_tag_order,
        });
    }
}



