#! /bin/bash
#------------------------------------------------------------------------------
#$Author$
#$Date$ 
#$Revision$
#$URL$
#------------------------------------------------------------------------------
#*
#   Deposit CIFs into COD database using CGI deposition interface.
#
#   Usage: $0 structure1.cif [structure2.cif ...]
#**

TMP_DIR="${TMPDIR}"

set -ue
## set -x

script() { echo "$*"; }
setvar() { eval $1="'$3'"; }

setvar Id = '$Id$'

setvar INPUT_CONFIG    = "${HOME:-.}/.cod_deposit.cfg"
setvar SERVER          = "http://test.crystallography.net"
setvar DEPOSIT_PATH    = "cgi-bin/cif-deposit.pl"
setvar DEPOSIT_URL     = "${SERVER}/${DEPOSIT_PATH}"
setvar DEPOSITION_TYPE = "published"

setvar FILES    = ''
setvar SEPARATE_OUT_DIR = ''
setvar SEPARATOR = ' '
setvar READ_STDIN = false

setvar DEBUG    = false
setvar PROGRESS = false
setvar REPLACE  = false
setvar RELEASE  = false
setvar OUTPUT_MODE  = "html"

setvar BASENAME = "`basename $0`"

# CIF_HEADER:
#
# curl http://www.crystallography.net/cod/cgi-bin/cif-deposit.pl -F
# header=crystaleye <kiti parametrai>
# 
# Taip pat galima nurodyti ir kitas mūsų naudojamas antraštes: 'common',
# 'amcsd' ir 'iucr'.
# 
setvar CIF_HEADER = common 

# Executables:

curl=curl

#** OPTIONS:
#**
#**  -c, --config config-file-with-password.cfg
#**      Specify which file holds depostor user name and
#**      password (default: ~/.cod_deposit.cfg
#**
#**  -h, --host  test.crystallography.net
#**      Specify host to commit structrues to
#**
#**  -p, --path  cgi-bin/cif-deposit.pl
#**      Specify script path within the host to use for structure upload
#**
#**  -u, --url  http://test.crystallography.net/cgi-bin/cif-deposit.pl
#**      Specify the full URL to use for structure uploading (default:
#**      combine --host and --path values using http:// protocol and /).
#**
#**  -d, --deposition-type published
#**      Specify the deposition type under which the structure is to be 
#**      deposited
#**
#**  -s, --separate-outputs folder-to-put-deposition-outputs/
#**      Specify a folder to put deposition output for each deposited file
#**
#**  --replace
#**      Specify that given files are replacements for previously
#**      deposited data
#**
#**  --common-cif-header      Use a standard COD CIF header (default)
#**  --iucr-cif-header        Use a COD CIF header agreed with IUCr
#**  --amcsd-cif-header       Use a COD CIF header agreed with R.D.
#**  --crystaleye-cif-header  Use a COD CIF header agreed with P.M.-R.
#**
#**  -P, --progress
#**      Ask cif-deposit.pl to report progress of the deposition.
#**
#**  --output-mode html
#**      Specify the output mode (from "html" and "stdout")
#**
#**  -D, --debug
#**      Request output of the progress information from cif-deposit.pl to the
#**      HTTP server log.
#**
#**  --help                   print short help message (this message) and exit
while [ $# -gt 0 ]
do
  case $1 in
      -c|--config|--confi|--conf|--con|--co|--co)
          INPUT_CONFIG="$2"
          shift
          ;;
      -h|--host|--hos|--ho|--h)
          SERVER="http://$2"
          DEPOSIT_URL="${SERVER}/${DEPOSIT_PATH}"
          shift
          ;;
      -p|--path)
          DEPOSIT_PATH="$2"
          DEPOSIT_URL="${SERVER}/${DEPOSIT_PATH}"
          shift
          ;;
      -u|--url|--ur|--u)
          DEPOSIT_URL="$2"
          shift
          ;;
      -s|--separate-outputs|--separate)
          SEPARATE_OUT_DIR="$2"
          shift
          ;;
      -d|--deposition-type)
          DEPOSITION_TYPE="$2"
          shift
          ;;
      -r|--read-stdin)
          READ_STDIN=true
          ;;
      -D|--debug|--debu|--deb|--de|--d)
          DEBUG=true
          ;;
      -D-|--no-debug|--no-debu|--no-deb|--no-de|--no-d)
          DEBUG=false
          ;;
      --output-mode)
          OUTPUT_MODE="$2"
          shift
          ;;
      -P|--progress|--progres|--progre|--progr|--prog|--pro|--pr|--p)
          PROGRESS=true
          ;;
      -P-|--no-progress|--no-progres|--no-progre|--no-progr|--no-prog|\
      --no-pro|--no-pr|--no-p)
          PROGRESS=false
          ;;
      --replace)
          REPLACE=true
          ;;
      --release|--release-data)
          RELEASE=true
          ;;
      --common-cif-header|--common-cif-heade|--common-cif-head|\
      --common-cif-hea|--common-cif-he|--common-cif-he|--common-cif|\
      --common-ci|--common-c|--common|--commo|--comm|--com)
          CIF_HEADER=common
          ;;
      --iucr-cif-header|--iucr-cif-heade|--iucr-cif-head|--iucr-cif-hea|\
      --iucr-cif-h|--iucr-cif|--iucr-ci|--iucr-c|--iucr|--iuc|--iu|--i)
          CIF_HEADER=iucr
          ;;
      --crystaleye-cif-header|--crystaleye-cif-heade|--crystaleye-cif-head|\
      --crystaleye-cif-hea|--crystaleye-cif-he|--crystaleye-cif-h|\
      --crystaleye-cif|--crystaleye-ci|--crystaleye-c|\
      --crystaleye|--crystaley|--crystale|--crystal|--crysta|--cryst|--crys|\
      --cry|--cr)
          CIF_HEADER=crystaleye
          ;;
      --amcsd-cif-header|--amcsd-cif-heade|--amcsd-cif-head|--amcsd-cif-hea|\
      --amcsd-cif-h|--amcsd-cif|--amcsd-ci|--amcsd-c|\
      --amcsd|--amcs|--amc|--am|--a)
          CIF_HEADER=amcsd
          ;;
      --script|--scrip|--scri|--scr|--sc|--s)
          curl="script curl"
          ;;
      --run|--ru|--r)
          curl=curl
          ;;
      --help|--hel|--he|--h)
            gawk '/^#\*/,/^#\*\*/ {
                    sub("^ *#[*]?[*]?", ""); \
                    gsub("\\$0","'$0'"); \
                    print $0
                }' $0
	    exit
	    ;;      
      -*) echo "`basename $0`: unknown option $1" >&2 ; exit 1 ;;
      *)  FILES="$FILES $1" ;;
    esac
    shift
done

## echo ${FILES}
eval set -- "${FILES}"

if [ $DEBUG = true ]
then
    DEBUG_ARG='-F debug=1'
else
    DEBUG_ARG=''
fi

if [ $PROGRESS = true ]
then
    PROGRESS_ARG='-F progress=1'
else
    PROGRESS_ARG=''
fi

if [ $REPLACE = true ]
then
    REPLACE_ARG='-F replace=1'
else
    REPLACE_ARG=''
fi

if [ $RELEASE = true ]
then
    RELEASE_ARG='-F release=1'
else
    RELEASE_ARG=''
fi

test -z "${TMP_DIR}" && TMP_DIR="/tmp"
TMP_DIR="${TMP_DIR}/tmp-${BASENAME}-$$"
umask 077
mkdir "${TMP_DIR}"

TMP_USERNAME="${TMP_DIR}/username"
TMP_PASSWRD="${TMP_DIR}/password"
TMP_EMAIL="${TMP_DIR}/user_email"
TMP_AUTHOR_NAME="${TMP_DIR}/author_name"
TMP_AUTHOR_EMAIL="${TMP_DIR}/author_email"
TMP_JOURNAL="${TMP_DIR}/journal"
TMP_CLIENT_IP="${TMP_DIR}/web_client_ip"
TMP_BYPASS_PASSWD="${TMP_DIR}/bypass_password"
TMP_MESSAGE="${TMP_DIR}/message"
TMP_DEPOSIT_LIST="${TMP_DIR}/deposition_list"

perl -lne "print \$1 if /^username=(.*)/" < ${INPUT_CONFIG} > ${TMP_USERNAME}
perl -lne "print \$1 if /^password=(.*)/" < ${INPUT_CONFIG} > ${TMP_PASSWRD}
perl -lne "print \$1 if /^journal=(.*)/"  < ${INPUT_CONFIG} > ${TMP_JOURNAL}
perl -lne "print \$1 if /^user_email=(.*)/"   < ${INPUT_CONFIG} > ${TMP_EMAIL}
perl -lne "print \$1 if /^author_name=(.*)/"  < ${INPUT_CONFIG} > ${TMP_AUTHOR_NAME}
perl -lne "print \$1 if /^author_email=(.*)/" < ${INPUT_CONFIG} > ${TMP_AUTHOR_EMAIL}
perl -lne "print \$1 if /^web_client_ip=(.*)/"   < ${INPUT_CONFIG} > ${TMP_CLIENT_IP}
perl -lne "print \$1 if /^bypass_password=(.*)/" < ${INPUT_CONFIG} > ${TMP_BYPASS_PASSWD}
perl -lne "print \$1 if /^message=(.*)/" < ${INPUT_CONFIG} > ${TMP_MESSAGE}
HOLD_PERIOD=$(perl -lne "print \$1 if /^hold_period=(.*)/" < ${INPUT_CONFIG})


if [ -s ${TMP_JOURNAL} ]
then
    JOURNAL_ARG="-F journal=<${TMP_JOURNAL}"
else
    JOURNAL_ARG=''
fi

if [ -s ${TMP_EMAIL} ]
then
    EMAIL_ARG="-F user_email=<${TMP_EMAIL}"
else
    EMAIL_ARG=''
fi

if [ -s ${TMP_AUTHOR_NAME} ]
then
    AUTHOR_NAME_ARG="-F author_name=<${TMP_AUTHOR_NAME}"
else
    AUTHOR_NAME_ARG=''
fi

if [ -s ${TMP_AUTHOR_EMAIL} ]
then
    AUTHOR_EMAIL_ARG="-F author_email=<${TMP_AUTHOR_EMAIL}"
else
    AUTHOR_EMAIL_ARG=''
fi

if [ -s ${TMP_CLIENT_IP} ]
then
    WEB_CLIENT_IP_ARG="-F web_client_ip=<${TMP_CLIENT_IP}"
else
    WEB_CLIENT_IP_ARG=''
fi

if [ -s ${TMP_BYPASS_PASSWD} ]
then
    BYPASS_PASSWD_ARG="-F bypass_check_password=<${TMP_BYPASS_PASSWD}"
else
    BYPASS_PASSWD_ARG=''
fi

if [ -s ${TMP_MESSAGE} ]
then
    MESSAGE_ARG="-F message=<${TMP_MESSAGE}"
else
    MESSAGE_ARG=''
fi

if [ -n "${HOLD_PERIOD}" ]
then
    HOLD_PERIOD_ARG="-F hold_period=${HOLD_PERIOD}"
else
    HOLD_PERIOD_ARG=''
fi

DEPOSIT_LOGGER="cat"

if [ ${READ_STDIN} = true ]
then
    cat "$@" > ${TMP_DEPOSIT_LIST}
else
    perl -e 'while( @ARGV ) { print shift( @ARGV ), "\n"; }' \
        ${FILES} > ${TMP_DEPOSIT_LIST}
fi

cat ${TMP_DEPOSIT_LIST} | \
    while read line
    do
        CIF=${line%${SEPARATOR}*}
        HKL=${line#*${SEPARATOR}}
        echo ${BASENAME}: ${CIF}: NOTE: Deposition started at $(date)
        CIF_ARG="-F cif=@${CIF};filename=$(basename ${CIF})"
        HKL_ARG=""
        if [ "${line}" != "${line/${SEPARATOR}/}" ]
            then HKL_ARG="-F hkl=@${HKL};filename=$(basename ${HKL})"
        fi
        if [ -n "${SEPARATE_OUT_DIR}" ]
        then
            DEPOSIT_LOGGER="cat > \"${SEPARATE_OUT_DIR}/$(basename $i .cif).html\""
        fi
        ${curl} \
            --silent \
            ${DEBUG_ARG} \
            ${PROGRESS_ARG} \
            ${REPLACE_ARG} \
            ${MESSAGE_ARG} \
            ${RELEASE_ARG} \
            -F header=${CIF_HEADER} \
            -F "output_mode=${OUTPUT_MODE}" \
            -F "username=<${TMP_USERNAME}" \
            -F "password=<${TMP_PASSWRD}" \
            ${JOURNAL_ARG} \
            ${EMAIL_ARG} \
            ${AUTHOR_NAME_ARG} \
            ${AUTHOR_EMAIL_ARG} \
            ${WEB_CLIENT_IP_ARG} \
            ${BYPASS_PASSWD_ARG} \
            ${HOLD_PERIOD_ARG} \
            ${CIF_ARG} \
            ${HKL_ARG} \
            -F "deposition_type=${DEPOSITION_TYPE}" \
            ${DEPOSIT_URL} \
            | eval ${DEPOSIT_LOGGER}
        echo ${BASENAME}: ${CIF}: NOTE: Deposition finished at $(date)
    done

if which wipe >/dev/null 2>&1
then
    wipe -rf "${TMP_DIR}"
else
    rm -rf "${TMP_DIR}"
fi
