#! /bin/sh
#!perl -w # --*- Perl -*--
eval 'exec perl -x $0 ${1+"$@"}'
    if 0;
#------------------------------------------------------------------------------
#$Author$
#$Date$ 
#$Revision$
#$URL$
#------------------------------------------------------------------------------
#*
#  Parse a CIF file
#**

use strict;
use lib "./lib/perl5";
use lib "./CIFParser";
use CIFParser;
use ShowStruct;
use File::Basename;

for my $filename (@ARGV) {
    my $parser = new CIFParser;
    my $data = $parser->Run($filename);

    if( defined $parser->YYData->{ERRCOUNT} && $parser->YYData->{ERRCOUNT} > 0 ) {
	print STDERR File::Basename::basename($0), ": " ,
	$parser->YYData->{ERRCOUNT},
	" error(s) encountered while parsing file '${filename}'\n";
	exit -1;
    }

    my $warnings = 0;
    for my $dataset (@$data) {
	if( !defined $dataset->{values} ) {
	    print "$0: $filename: no values?!\n";
	    next;
	}
	my $values = $dataset->{values};
	if( !defined $values->{_journal_name_full} ) {
	    print "$0: $filename: _journal_name_full is undefined\n";
	    $warnings ++;
	}
	if( !defined $values->{_journal_year} &&
	    !defined $values->{_journal_volume} ) {
	    print "$0: $filename: neither _journal_year nor " .
		  "_journal_volume is defined\n";
	    $warnings ++;
	}
	if( !defined $values->{_journal_page_first} ) {
	    print "$0: $filename: _journal_page_first is undefined\n";
	    $warnings ++;
	}
	if( !defined $values->{_publ_author_name} ) {
	    print "$0: $filename: no _publ_author_name\n";
	    $warnings ++;
	}
    }
    printf "%-30s: OK\n", $filename if $warnings == 0;
}
