#! /bin/sh
#!perl -w # --*- Perl -*--
eval 'exec perl5 -x $0 ${1+"$@"}'
    if 0;
#------------------------------------------------------------------------------
#$Author$
#$Date$ 
#$Revision$
#$URL$
#------------------------------------------------------------------------------
#*
#  Convert Pubmed XML bibliography records to may own XML-like markup
#**

use strict;

for my $file (@ARGV) {
    open( F, $file ) or die "$0: could not open file '$file' for reading";
    
    local $/; #  enable "slurp" mode: read the whole header file.

    my $xml = <F>; # read in the whole XML file

    ## print $xml;

    if( $xml =~ m|<PubmedArticleSet.*?>(.*?)</PubmedArticleSet>|ms ) {
	my $article_set = $1;
	## print "$article_set = $article_set\n";
	while( $article_set =~ s|<PubmedArticle.*?>(.*?)</PubmedArticle>||ms ) {
	    my $article = $1;
	    ## print "$article = $article\n";
	    $article =~ m|<Title.*?>(.*?)</Title>|ms;
	    my $journal = $1;
	    $article =~ m|<ArticleTitle.*?>(.*?)</ArticleTitle>|ms;
	    my $title = $1;
	    $article =~ m|<Year.*?>(.*?)</Year>|ms;
	    my $year = $1;
	    $article =~ m|<Issue.*?>(.*?)</Issue>|ms;
	    my $issue = $1;
	    $article =~ m|<Volume.*?>(.*?)</Volume>|ms;
	    my $volume = $1;

	    my $pages = "";
	    if( $article =~ m|<MedlinePgn.*?>(.*?)</MedlinePgn>| ) {
		$pages = $1;
	    } else {
		$article =~ m|<Pagination.*?>(.*?)</Pagination>|;
		$pages = $1;
		$pages =~ m/(\d+\s*(:?-\s*\d+)?)/;
		$pages = $1;
	    }

	    $article =~ m|<AuthorList.*?>(.*?)</AuthorList>|ms;
	    my $author_list = $1;

	    print "<authors separator=\";\">";
	    my $separator = "";
	    while( $author_list =~ s|<Author.*?>(.*?)</Author>||ms ) {
		my $author = $1;
		$author =~ m|<LastName.*?>(.*?)</LastName>|;
		my $last = $1;
		my $first;
		if( $author =~ m|<ForeName.*?>(.*?)</ForeName>| ) {
		    $first = $1;
		} else {
		    if( $author =~ m|<FirstName.*?>(.*?)</FirstName>| ) {
			$first = $1;
		    }
		    if( $author =~ m|<MiddleName.*?>(.*?)</MiddleName>| ) {
			$first .= " " . $1;
		    }
		}
		my $junior;
		if( $author =~ m|<Suffix.*?>(.*?)</Suffix>| ) {
		    $junior = $1;
		}
		my $author_name = $last;
		if( defined $junior ) {
		    $author_name .= ", " . $junior;
		}
		$author_name .= ", " . $first;
		print $separator, $author_name;
		$separator = "; ";
	    }
	    print "</authors>\n";

	    print "<title>$title</title>\n";
	    print "<journal>$journal</journal>\n";
	    print "<year>$year</year>\n";
	    print "<volume>$volume</volume>\n";
	    print "<issue>$issue</issue>\n";
	    print "<pages>$pages</pages>\n";
	    print "\n";
	}
    }

    close F;
}
