#! /bin/sh
#!perl -w # --*- Perl -*--
eval 'exec perl5 -x $0 ${1+"$@"}'
    if 0;
#------------------------------------------------------------------------------
#$Author$
#$Date$ 
#$Revision$
#$URL$
#------------------------------------------------------------------------------
#*
#  Perl script ...
#**

use strict;

use File::Basename;

use LWP::UserAgent;
use LWP::Simple;
use HTTP::Request;
use HTTP::Headers;

my $doi_prefix = "10.1021"; # JACS prefix
## my $query_url = "http://www.ncbi.nlm.nih.gov/entrez/eutils";
my $query_url = "http://eutils.ncbi.nlm.nih.gov/entrez/eutils";


for my $file (@ARGV) {
    my $doi_suffix = substr(
	File::Basename::basename( $file, '\.cif|\.txt' ), 0, 9
    );
    my $doi = $doi_prefix . "/" . $doi_suffix;

    my $query = "$query_url/esearch.fcgi?" .
	"db=pubmed&term=$doi\[AID\]";

    my $esearch_result = get( $query );

    ## print $esearch_result;

    if( $esearch_result =~ m|<Id>(\d+)</Id>| ) {
	my $id = $1;
	## print $id, "\n";
	$query = "$query_url/efetch.fcgi?" .
	    "db=pubmed&tool=$0&email=grazulis\@ibt.lt&id=$id&retmode=xml";
	$esearch_result = get( $query );
	print $esearch_result, "\n";
    } else {
	print STDERR "$0: Id for '$file' not found in Medline\n";
    }
}
