#! /bin/sh
#!perl -w # --*- Perl -*--
eval 'exec perl5 -x $0 ${1+"$@"}'
    if 0;
#------------------------------------------------------------------------------
#$Author$
#$Date$ 
#$Revision$
#$URL$
#------------------------------------------------------------------------------
#*
#  Convert Pubmed XML bibliography records to may own XML-like markup
#**

use strict;

for my $file (@ARGV) {
    open( F, $file ) or die "$0: could not open file '$file' for reading";
    
    local $/; #  enable "slurp" mode: read the whole header file.

    my $xml = <F>; # read in the whole XML file

    ## print $xml;

    if( $xml =~ m|<PubmedArticleSet.*?>(.*?)</PubmedArticleSet>|ms ) {
	my $article_nr = 0;
	my $article_set = $1;
	## print "$article_set = $article_set\n";
	while( $article_set =~ s|<PubmedArticle.*?>(.*?)</PubmedArticle>||ms ) {
	    my $article = $1;
	    ## print "$article = $article\n";
	    $article_nr ++;

	    my $journal;
	    if( $article =~ m|<Title.*?>(.*?)</Title>|ms ) {
		$journal = $1;
	    } else {
		print STDERR "$0: no <Title> (Journal title) " .
		    "found in the file '$file' article $article_nr\n";
		die;
	    }

	    my $title;
	    if( $article =~ m|<ArticleTitle.*?>(.*?)</ArticleTitle>|ms ) {
		$title = $1;
	    } else {
		print STDERR "$0: no <ArticleTitle> found in the file '$file' ".
		    "article $article_nr\n";
		die;
	    }

	    my $year;
	    if( $article =~ m|<Year.*?>(.*?)</Year>|ms ) {
		$year = $1;
	    } else {
		print STDERR "$0: no <Year> found in the file '$file' ".
		    "article $article_nr\n";
		die;
	    }

	    my $issue;
	    if( $article =~ m|<Issue.*?>(.*?)</Issue>|ms ) {
		$issue = $1;
	    }

	    my $volume;
	    if( $article =~ m|<Volume.*?>(.*?)</Volume>|ms ) {
		$volume = $1;
	    }

	    my $pages = "";
	    if( $article =~ m|<MedlinePgn.*?>(.*?)</MedlinePgn>| ) {
		$pages = $1;
	    } elsif( $article =~ m|<Pagination.*?>(.*?)</Pagination>| ){
		$pages = $1;
		$pages =~ m/(\d+\s*(:?-\s*\d+)?)/;
		$pages = $1;
	    } else {
		print STDERR "$0: no <MedlinePgn> or <Pagination> " .
		    "found in the file '$file' ".
		    "article $article_nr\n";
		die;
	    }

	    if( $article =~ m|<AuthorList.*?>(.*?)</AuthorList>|ms ) {
		my $author_list = $1;

		print "<authors separator=\";\">";
		my $separator = "";
		while( $author_list =~ s|<Author.*?>(.*?)</Author>||ms ) {
		    my $author = $1;
		    $author =~ m|<LastName.*?>(.*?)</LastName>|;
		    my $last = $1;
		    my $first;
		    if( $author =~ m|<ForeName.*?>(.*?)</ForeName>| ) {
			$first = $1;
		    } else {
			if( $author =~ m|<FirstName.*?>(.*?)</FirstName>| ) {
			    $first = $1;
			}
			if( $author =~ m|<MiddleName.*?>(.*?)</MiddleName>| ) {
			    $first .= " " . $1;
			}
		    }
		    my $junior;
		    if( $author =~ m|<Suffix.*?>(.*?)</Suffix>| ) {
			$junior = $1;
		    }
		    my $author_name = $last;
		    if( defined $junior ) {
			$author_name .= ", " . $junior;
		    }
		    $author_name .= ", " . $first;
		    print $separator, $author_name;
		    $separator = "; ";
		}
	    } # if AuthorList

	    print "</authors>\n";

	    print "<title>$title</title>\n";
	    print "<journal>$journal</journal>\n";
	    print "<year>$year</year>\n";
	    print "<volume>$volume</volume>\n" if defined $volume;
	    print "<issue>$issue</issue>\n" if defined $issue;
	    print "<pages>$pages</pages>\n";
	    print "\n";
	}
    } else {
	print STDERR "$0: <PubmedArticleSet> is not found in file '$file'\n";
    }

    close F;
}
