#! /bin/sh
#!perl -w # --*- Perl -*--
eval 'exec perl -x $0 ${1+"$@"}'
    if 0;
#------------------------------------------------------------------------------
#$Author:$
#$Date:$ 
#$Revision:$
#$URL:$
#------------------------------------------------------------------------------
#*
#  Perl script ...
#**

use strict;
use lib ".";
use formula_sum;

my $p = new formula_sum;

$p->Run($ARGV[0]);
$p->PrintFormula;
