#!/usr/bin/python
# -*- coding: utf-8 -*-
#------------------------------------------------------------------------------
#$Author$
#$Revision$
#$URL$
#$Date$
#$Id$
#------------------------------------------------------------------------------
#*
#  Test driver for ccifparser.py module.
#**
import sys
import cod.ccifparser

filename = sys.argv.pop()
options = {}
for arg in sys.argv[1:]:
    options[arg] = 1

cod.ccifparser.parse( filename, options )
