#!/bin/bash
#------------------------------------------------------------------------------
#$Author$
#$Date$
#$Revision$
#$URL$
#------------------------------------------------------------------------------
#*
# Generate release tarballs for the most recently released tags, sign
# them and calculate checksums.
#**

REPO=$(svn info --show-item repos-root-url $0)
PROJECT=$(basename ${REPO})

VERSION=$(svn list ${REPO}/tags \
            | sed 's/^v//; s/\/$//' \
            | sort --version-sort --reverse \
            | head -n 1)

REVISION=$(svn log --limit 1 -r0:HEAD --stop-on-copy ${REPO}/tags/v${VERSION} \
            | tail -n +2 \
            | head -n 1 \
            | perl -lne 'print $1 if /^r(\d+)/')

test -z "${REVISION}" && exit 1

LC_ALL=en_US.UTF-8 svn export -r ${REVISION} ${REPO}/tags/v${VERSION} ${PROJECT}-${VERSION}

tar -czf ${PROJECT}-${VERSION}.tar.gz ${PROJECT}-${VERSION}
tar -cjf ${PROJECT}-${VERSION}.tbz2   ${PROJECT}-${VERSION}

for ARCHIVE in ${PROJECT}-${VERSION}.tar.gz ${PROJECT}-${VERSION}.tbz2
do
    gpg --sign --armor --detach ${ARCHIVE}
    md5sum  ${ARCHIVE} > ${ARCHIVE}.md5
    sha1sum ${ARCHIVE} > ${ARCHIVE}.sha1
done
