
function_object_bases.h:	../core/hkl_datatypes.h ../core/xmap.h ../core/nxmap_operator.h 

function_object_bases.o:	function_object_bases.cpp function_object_bases.h 

sfcalc.h:               	function_object_bases.h 

sfcalc.o:               	sfcalc.cpp sfcalc.h ../core/atomsf.h 

edcalc.h:               	function_object_bases.h 

edcalc.o:               	edcalc.cpp edcalc.h ../core/atomsf.h 

sfcalc_obs.h:           	function_object_bases.h 

sfcalc_obs.o:           	sfcalc_obs.cpp sfcalc_obs.h edcalc.h ../core/hkl_compute.h ../core/resol_targetfn.h 

sfweight.h:             	function_object_bases.h 

sfweight.o:             	sfweight.cpp sfweight.h ../core/hkl_operators.h ../core/resol_targetfn.h 

fffear.h:               	function_object_bases.h 

fffear.o:               	fffear.cpp fffear.h ../core/map_interp.h 

mapfilter.h:            	function_object_bases.h 

mapfilter.o:            	mapfilter.cpp mapfilter.h 

skeleton.h:             	function_object_bases.h 

skeleton.o:             	skeleton.cpp skeleton.h ../core/map_utils.h 

originmatch.h:          	function_object_bases.h 

originmatch.o:          	originmatch.cpp originmatch.h 

